### ISSUE TITLE
Bump @primer/components to the latest version

### ISSUE THREAD

**Issue by colebemis** [primer/doctocat#253]
## Problem

Doctocat is using an outdated version of [Primer React](https://primer.style/react). Primer React is currently on v29.0.0 but Doctocat uses Primer React v20.0.0

## Tasks

- [ ] Bump `@primer/components` to the latest version
- [ ] Fix breaking changes
  - [ ] Replace presentational color variables (`color="text.gray"`) with functional variables (`color="fg.default"`)
